export const config = {
  json_fields: {
    'T/A': 'Tipo',
    'CPF': 'Cpf',
    'NOME COMPLETO': 'Nome',
    'Nº PASSAPORTE': 'PassaporteNumero',
    'DATA DE VALIDADE - DIA': 'PassaporteValidadeDia',
    'DATA DE VALIDADE - MÊS': 'PassaporteValidadeMes',
    'DATA DE VALIDADE - ANO': 'PassaporteValidadeAno',
    'DATA DE EXPEDIÇÃO - DIA': 'PassaporteExpedicaoDia',
    'DATA DE EXPEDIÇÃO - MÊS': 'PassaporteExpedicaoMes',
    'DATA DE EXPEDIÇÃO - ANO': 'PassaporteExpedicaoAno',
    'RG': 'Rg',
    'SEXO': 'Sexo',
    'DATA DE NASCIMENTO - DIA': 'DataNascimentoDia',
    'DATA DE NASCIMENTO - MÊS': 'DataNascimentoMes',
    'DATA DE NASCIMENTO - ANO': 'DataNascimentoAno',
    'ENDEREÇO': 'Endereco',
    'BAIRRO': 'Bairro',
    'CIDADE': 'Cidade',
    'CEP': 'Cep',
    'ESTADO': 'Estado',
    'DDD': 'Ddd1',
    'TELEFONE RESIDENCIAL': 'TelefoneResidencial',
    'DDD ': 'Ddd2',
    'CELULAR': 'Celular',
    'EMAIL': 'Email',
    'NOME CONTATO EMERGÊNCIA': 'NomeContatoEmergencia',
    'DDD  ': 'Ddd3',
    'TELEFONE EMERGÊNCIA': 'TelefoneEmergencia',
    'TAMANHO CAMISETA': 'TamanhoCamiseta',
    'AEROPORTO - ORIGEM': 'AeroportoOrigem',
    'AEROPORTO - RETORNO': 'AeroportoDestino',
    'CONDIÇÃO MÉDICA ESPECAL': 'CondicaoMedicaEspecial',
    'SE SIM QUAL? ': 'CondicaoMedicaEspecialQual',
    'MEDICAMENTOS': 'Medicamentos',
    'SE SIM QUAL?  ': 'MedicamentosQual',
    'RESTRIÇÃO ALIMENTAR': 'RestricaoAlimentar',
    'SE SIM QUAL?   ': 'RestricaoAlimentarQual',
    'Data 1': 'Vazio',
    'Cia/Voo 1': 'Vazio',
    'Trecho 1': 'Vazio',
    'Saída 1': 'Vazio',
    'Chegada 1': 'Vazio',
    'Data 2': 'Vazio',
    'Cia/Voo 2': 'Vazio',
    'Trecho 2': 'Vazio',
    'Saída 2': 'Vazio',
    'Chegada 2': 'Vazio',
    'Data 3': 'Vazio',
    'Cia/Voo 3': 'Vazio',
    'Trecho 3': 'Vazio',
    'Saída 3': 'Vazio',
    'Chegada 3': 'Vazio',
    'Data 4': 'Vazio',
    'Cia/Voo 4': 'Vazio',
    'Trecho 4': 'Vazio',
    'Saída 4': 'Vazio',
    'Chegada 4': 'Vazio',
    'Data 5': 'Vazio',
    'Cia/Voo 5': 'Vazio',
    'Trecho 5': 'Vazio',
    'Saída 5': 'Vazio',
    'Chegada 5': 'Vazio',
    'Data 6': 'Vazio',
    'Cia/Voo 6': 'Vazio',
    'Trecho 6': 'Vazio',
    'Saída 6': 'Vazio',
    'Chegada 6': 'Vazio',
    'Localizador': 'Vazio',
    'Data 1 ': 'Vazio',
    'Cia/Voo 1 ': 'Vazio',
    'Trecho 1 ': 'Vazio',
    'Saída 1 ': 'Vazio',
    'Chegada 1 ': 'Vazio',
    'Data 2 ': 'Vazio',
    'Cia/Voo 2 ': 'Vazio',
    'Trecho 2 ': 'Vazio',
    'Saída 2 ': 'Vazio',
    'Chegada 2 ': 'Vazio',
    'Data 3 ': 'Vazio',
    'Cia/Voo 3 ': 'Vazio',
    'Trecho 3 ': 'Vazio',
    'Saída 3 ': 'Vazio',
    'Chegada 3 ': 'Vazio',
    'Data 4 ': 'Vazio',
    'Cia/Voo 4 ': 'Vazio',
    'Trecho 4 ': 'Vazio',
    'Saída 4 ': 'Vazio',
    'Chegada 4 ': 'Vazio',
    'Data 5 ': 'Vazio',
    'Cia/Voo 5 ': 'Vazio',
    'Trecho 5 ': 'Vazio',
    'Saída 5 ': 'Vazio',
    'Chegada 5 ': 'Vazio',
    'Data 6 ': 'Vazio',
    'Cia/Voo 6 ': 'Vazio',
    'Trecho 6 ': 'Vazio',
    'Saída 6 ': 'Vazio',
    'Chegada 6 ': 'Vazio',
    'Localizador ': 'Vazio'
  },
  json_meta: [
    [{
      'key': 'charset',
      'value': 'utf-8'
    }]
  ]
}

export const columns = [{
    label: "Nome Completo",
    field: "Nome"
  },
  {
    label: "Cpf",
    field: "Cpf"
  },
  {
    label: "RG",
    field: "Rg"
  },
  {
    label: "Sexo",
    field: "Sexo"
  },
  {
    label: "Cidade",
    field: "Cidade"
  },
  {
    label: "Estado",
    field: "Estado"
  }
]
